install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')

install.packages("CHNOSZ")
install.packages("dplyr")
install.packages("stringr")
install.packages("tools")
